language: python
sudo: required
python:
  - "2.7"
#before_install:
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel cython
  - pip install coveralls
  - pip install flake8
  - pip install fonttools
  - pip install booleanOperations
  - pip install fontMath
  - pip install robofab
  - pip install defcon
  - pip install mutatorMath
  - pip install ufolib
  - pip install ufonormalizer

script:
  - cd afdko/Tools/SharedData/FDKScripts
  - flake8 CheckOutlinesUFO.py
  - coverage run --source=CheckOutlinesUFO.py CheckOutlinesUFO.py --test
after_success:
  - coveralls
notifications:
  slack: typekit:y89H3n4sxK0ORpapm8zHDu3l
